language: cpp
compiler: gcc
dist: trusty

env:
  global:
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow -pg"
    # Misc, we will use this once we setup unit tests
    #- RUN_TESTS=true
    #- COVERAGE=false

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install cmake
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script:
  # Build
  - scripts/ci_build.sh
  # Produce the gprof log
  - scripts/ci_profiling.sh

after_success:
  - echo "Successful!"

after_failure:
  - echo "Failed!"

# Currently not used
#deploy:
#  github-token: $GITHUB_TOKEN
